name: Generate Snake Game
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Snake Game
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: MVConsorte
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Check if build dir exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Build directory does not exist. Creating it now."
            mkdir dist
          fi
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
